# Generated by Django 3.2.4 on 2021-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindoor1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='humedad_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='humedad_minima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='temperatura_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='temperatura_minima',
            field=models.IntegerField(),
        ),
    ]
