# Generated by Django 3.2.4 on 2021-07-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindoor1', '0002_auto_20210721_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='hora_apagado',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hora_encendido',
            field=models.TimeField(),
        ),
    ]
